### ISSUE TITLE
Missing directory 

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-migrations-and-alembic#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

Configuring a Migration Environment: "Next, navigate into app/db.py to start designing our database with SQLAlchemy."- app/db.py doesn't exist it must be created 

__init__.py needs to be created as well but is never mentioned. It would be helpful to explain the purpose of this file as well. 

### Suggested Changes

Add the directory or add a paragraph instructing students to add it.

**Comment by professor-ben** [comment]
phasing __init__.py out- updated directory structure so that it is not needed.
