### ISSUE TITLE
Pipfile.lock problem

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-migrations-and-alembic#12]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

When coding along, I had to delete the Pipfile.lock and reinstall in order to successfully use the `alembic init migrations` command. Otherwise I received a "Module Not Found Error":

```
ModuleNotFoundError: No module named 'importlib_resources'
```

Maybe we tell students to do that when they're forking and cloning down this lab?

**Comment by professor-ben** [comment]
This was just fixed as a part of a fix to one of your earlier tickets- thanks for creating this issue!

-Ben
