### ISSUE TITLE
create models.py file?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-migrations-and-alembic#14]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

In the **Configuring a Migration Environment** section, we tell students to navigate into their `models.py` file. However, that file doesn't come built in with the code that students clone down, so they'll have to make it for themselves. We should probably tell them to do so, and in what directory to make it, to avoid confusion on their part. (I'm guessing we make it in the `app` directory, correct?)

**Comment by Matt-Eva** [comment]
I see now that we have models.py listed as being under the app folder when students run their tree command. It could still be helpful to explicitly tell students that they need to create the models.py file within their app folder

**Comment by professor-ben** [comment]
Clarified! Thanks for raising this issue.

-Ben
