### ISSUE TITLE
What's the importance of down_revision?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-migrations-and-alembic#16]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

We mention that our second migration we generated has a `down_revision`, which points to the previous migration ID. What is the significance of a `down_revision`? How is it being used by Alembic and SQLAlchemy? If we're going to bring it up as a concept, we should probably give it some context.

**Comment by professor-ben** [comment]
I clarified it a bit in the lesson, along with a couple other tweaks.
