### ISSUE TITLE
Database Viewer Extension

### ISSUE THREAD

**Issue by sbalayan1** [learn-co-curriculum/python-p3-migrations-and-alembic#18]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

By the end of the lab, it seems like we should be able to open the database and view the alembic_version and students tables. No extension was provided for this.  

### Suggested Changes

Provide the extension to install to make database viewable in vs code

**Comment by professor-ben** [comment]
Hi Sean,

We introduced a SQLite VSCode extension back in the SQL Fundamentals module. Do you think it would be helpful to throw that in at the beginning of SQLAlchemy as well?

-Ben

**Comment by sbalayan1** [comment]
Yeah that's what I figured. Def think it would be a helpful link in the off chance a student forgets to install it. 

-Sean
