### ISSUE TITLE
Running `alembic upgrade head`

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-migrations-and-alembic#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

Generating our First Migration: It’s not super clear that `alembic upgrade head` needed to be run after the migration was generated. 

### Suggested Changes

Be a bit more explicit here.

**Comment by professor-ben** [comment]
conditionals changed to imperatives
