### ISSUE TITLE
sessionmaker

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-migrations-and-alembic#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

Configuring a Migration Environment:  I don't think we are using `from sqlalchemy.orm import sessionmaker` In this example and it's missing from the example in Autogenerating a Migration I don't think it's needed unless I missed something.

**Comment by professor-ben** [comment]
good catch- deleted.
