### ISSUE TITLE
Context for deliverables 

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-migrations-and-alembic#4]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204248?module_item_id=468030

### Concern

Instructions: I don't think there's enough context here to help students figure out this deliverable. Explicit instruction would be helpful here.

### Suggested Changes

Add more explicit deliverables or another example.

**Comment by professor-ben** [comment]
removed deliverable, reformatted as code-along.
